// Banco editable: correcta es 0 (A), 1 (B) o 2 (C).
// Consecuencias: back1, back2, skip, return, rebound, retry.
const CATEGORIAS = [
  {nombre:'Ciudadanía digital',color:'#e0eab7'},
  {nombre:'Información sensible',color:'#cbe7e1'},
  {nombre:'Phishing',color:'#f8dfaa'},
  {nombre:'Ciberbullying',color:'#e1d7f0'},
  {nombre:'Grooming',color:'#f5d5ce'},
  {nombre:'Fake news / IA',color:'#cfe2f3'},
  {nombre:'Ludopatía adolescente',color:'#f1d9e6'}
];
const PREGUNTAS = [
 {categoria:0,situacion:'Tu grupo quiere publicar fotos de una actividad. Una compañera no quiere aparecer. ¿Qué hacen?',opciones:['Publican porque es una actividad escolar.','Piden permiso y eligen una imagen donde ella no aparezca.','Publican sin etiquetarla.'],correcta:1,explicacion:'Participar de una actividad no implica aceptar que se publique nuestra imagen. Respetar esa decisión es parte de la convivencia digital.',consecuencia:'back1',dificultad:'Fácil'},
 {categoria:0,situacion:'En un foro del curso alguien propone una idea con la que no estás de acuerdo. ¿Cómo participás?',opciones:['Explico mi desacuerdo con respeto y argumentos.','Comparto una captura para que otros se rían.','Le digo que deje de participar.'],correcta:0,explicacion:'Podemos disentir sin atacar a la persona. Los argumentos y la escucha ayudan a construir espacios donde todos puedan participar.',consecuencia:'rebound',dificultad:'Fácil'},
 {categoria:1,situacion:'Vas a subir una foto de tu entrada a un recital. Se ve el código QR. ¿Qué conviene hacer?',opciones:['Subirla solo a historias, porque desaparece.','Publicarla si no aparece tu nombre.','Ocultar el código y los datos antes de compartir.'],correcta:2,explicacion:'Un código de acceso puede ser usado por otra persona. Que una historia desaparezca no impide que alguien haga una captura.',consecuencia:'back2',dificultad:'Intermedia'},
 {categoria:1,situacion:'Una app de filtros pide tu dirección y acceso permanente a la ubicación. ¿Qué hacés?',opciones:['Acepto todo para probarla.','Reviso para qué lo necesita y evito permisos innecesarios.','Acepto porque una app popular siempre es segura.'],correcta:1,explicacion:'Antes de compartir datos conviene revisar su finalidad. Una función de filtros no justifica por sí sola conocer dónde estás todo el tiempo.',consecuencia:'return',dificultad:'Intermedia'},
 {categoria:2,situacion:'Un mensaje dice que tu cuenta se cerrará hoy y te pide entrar a un enlace para escribir tu contraseña. ¿Qué hacés?',opciones:['Abro la app oficial por mi cuenta para verificar el aviso.','Entro al enlace porque tiene el logo correcto.','Respondo con la contraseña para evitar el cierre.'],correcta:0,explicacion:'Los logos se pueden copiar y la urgencia puede usarse para engañar. Verificá desde la aplicación o dirección oficial que ya conocés.',consecuencia:'skip',dificultad:'Intermedia'},
 {categoria:2,situacion:'Un contacto te pide un código de verificación que acaba de llegar a tu teléfono. ¿Qué hacés?',opciones:['Se lo paso si su foto de perfil es conocida.','Se lo paso y después cambio la contraseña.','No comparto el código y verifico por otro medio qué ocurre.'],correcta:2,explicacion:'Los códigos de verificación pueden permitir el acceso a tu cuenta. Incluso una cuenta conocida puede haber sido comprometida.',consecuencia:'retry',dificultad:'Intermedia'},
 {categoria:3,situacion:'En el grupo circulan memes que humillan a un compañero y él pidió que paren. ¿Qué podés hacer?',opciones:['Reenviarlos a otro grupo para preguntar qué opinan.','No difundirlos, acompañarlo y buscar ayuda de una persona adulta de confianza.','Esperar a que se acostumbre.'],correcta:1,explicacion:'Acompañar y frenar la difusión ayuda. Pedir apoyo permite abordar el daño; no es responsabilidad de quien sufre el acoso resolverlo solo.',consecuencia:'back1',dificultad:'Fácil'},
 {categoria:3,situacion:'Una compañera te cuenta que recibe mensajes humillantes repetidos y teme contarlo. ¿Cómo respondés?',opciones:['La escucho sin culparla y la acompaño a pedir ayuda.','Le digo que cierre todas sus cuentas y lo olvide.','Le sugiero responder con insultos para defenderse.'],correcta:0,explicacion:'Escuchar y acompañar puede reducir el aislamiento. Con apoyo adulto se puede evaluar cómo guardar evidencia, reportar y detener el acoso.',consecuencia:'rebound',dificultad:'Intermedia'},
 {categoria:4,situacion:'Alguien que conociste jugando te ofrece regalos y pide que mantengas sus conversaciones en secreto frente a las personas adultas que te cuidan. ¿Qué hacés?',opciones:['Acepto porque jugamos hace varias semanas.','Le envío más datos para demostrar confianza.','No sigo sus pedidos y busco ayuda de una persona adulta de confianza.'],correcta:2,explicacion:'Los regalos y los pedidos de secreto pueden usarse para manipular. No tenés que enfrentar la situación a solas ni demostrar confianza compartiendo información.',consecuencia:'return',dificultad:'Intermedia'},
 {categoria:4,situacion:'Un contacto amenaza con publicar una imagen privada si no le enviás más. ¿Cuál es la mejor decisión?',opciones:['Enviar otra imagen para que se calme.','Pedir ayuda a una persona adulta de confianza sin ceder a la amenaza.','Pagarle para asegurarte de que borre todo.'],correcta:1,explicacion:'La responsabilidad es de quien amenaza. Ceder no garantiza que pare. Buscá apoyo para protegerte y evaluar cómo conservar mensajes y reportar sin difundir imágenes privadas.',consecuencia:'back2',dificultad:'Intermedia'},
 {categoria:5,situacion:'Circula un audio atribuido a la dirección que anuncia la suspensión de clases. ¿Qué hacés antes de reenviarlo?',opciones:['Consulto los canales oficiales de la escuela.','Lo reenvío si la voz parece real.','Creo el mensaje porque ya lo compartieron muchas personas.'],correcta:0,explicacion:'Una voz puede imitarse y un mensaje puede estar fuera de contexto. Consultar la fuente original permite verificar el anuncio.',consecuencia:'retry',dificultad:'Intermedia'},
 {categoria:5,situacion:'Una IA te da un dato sorprendente para un trabajo, pero no encontrás la fuente que menciona. ¿Qué hacés?',opciones:['Lo uso porque la respuesta está bien escrita.','Pongo esa fuente sin abrirla.','Contrasto el dato con fuentes verificables antes de usarlo.'],correcta:2,explicacion:'Una respuesta convincente puede contener errores o referencias inventadas. Verificar las fuentes forma parte del trabajo, aunque se use IA.',consecuencia:'skip',dificultad:'Intermedia'},
 {categoria:6,situacion:'Un amigo perdió dinero apostando y pide un préstamo para recuperarlo con otra apuesta. ¿Qué hacés?',opciones:['Le presto si promete devolverlo pronto.','No financio más apuestas; lo escucho y lo acompaño a pedir apoyo.','Busco con él una apuesta que parezca segura.'],correcta:1,explicacion:'Apostar de nuevo no garantiza recuperar lo perdido y puede aumentar las pérdidas. Acompañar sin juzgar y buscar apoyo es más útil que financiar nuevas apuestas.',consecuencia:'back2',dificultad:'Intermedia'},
 {categoria:6,situacion:'Un influencer ofrece un código para apostar y muestra solo sus ganancias. ¿Qué conviene pensar?',opciones:['Puede ser publicidad y omitir pérdidas; no demuestra que ganar sea fácil.','Si muestra capturas, cualquier persona puede repetir sus resultados.','Un código promocional elimina el riesgo de perder.'],correcta:0,explicacion:'Una promoción puede mostrar una parte interesada de la historia. Ni las capturas ni los bonos garantizan ganancias o eliminan el riesgo.',consecuencia:'back1',dificultad:'Intermedia'}
];
